Milestone 8: Recipe App
shyusu4/Recipe-App pull request #16
Opened 2023-01-13 19:06 UTC by shyusu4

## PR Description
- Used database migration files to maintain database schema
- Used validations for models
- Secured app from `N+1` problems
- Wrote SQL queries with ActiveRecord
- Set up associations between models
- Built a web app that requires the user to log in
- Described the difference between authorization and authentication
- Use Devise gem for authentication
- Understood how sessions and cookies can support authentication
- Limited access to web app resources based on authorization rules

2023-01-13 22:43 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @shyusu4,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-13 22:43 UTC, Omar-Muhamad commented on app/views/recipes/index.html.erb
> +      <% end %>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#:~:text=You%20should%20follow%20the%20layout%20of%20the%20wireframes%20provided.), Please stick to the given wireframe design and the placement of the elements and take care of the contrast ratio between font color and background color.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/212431436-a9dbfbed-1479-4a70-ab88-7f0261698552.png)  | ![image](https://user-images.githubusercontent.com/68796232/212431407-46545598-24cf-461f-b2a3-d6ccf13359e7.png)  |

2023-01-13 22:43 UTC, Omar-Muhamad commented on app/views/recipes/show.html.erb
> +						<%= recipe_food.foods.name %>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#:~:text=You%20should%20follow%20the%20layout%20of%20the%20wireframes%20provided.), Please center the element in the page to match the given wireframe design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/212432027-7e1f49f0-d560-489a-a429-c854ae3c3d9d.png) | ![image](https://user-images.githubusercontent.com/68796232/212432004-ca70bf05-4dcd-48b2-9fe6-1b199e1d15b0.png)  |

2023-01-13 22:43 UTC, Omar-Muhamad commented on app/views/recipe_foods/new.html.erb
> +  </div>
- [ ] There is an error raised when I try to add ingredients to a recipe, Please fix that.

![image](https://user-images.githubusercontent.com/68796232/212432391-d9e24ae5-0a32-4d58-80bd-41d93845f944.png)

2023-01-14 14:18 UTC, uwadonat approved these changes
## Hi @shyusu4,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Good commit history ✔️
- Professional pull request message ✔️


![209362895-9762f2f8-13cf-4ce0-90b6-a672c4f04196](https://user-images.githubusercontent.com/65860678/212476463-5c998cd1-dbf2-4575-a0e0-1bcccdd8d1af.gif)


# Status: Approved ✔️✔️✔️
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-14 15:03 UTC, merged